/**
 * Auto-generated by scripts/sync-hadar-corpus.mjs — DO NOT EDIT BY HAND.
 * Source of truth: /Users/work/hadar-transcripts/HADAR_RAW_QUOTES.md
 * Generated at: 2026-07-10T13:37:02.685Z
 *
 * To update: edit HADAR_RAW_QUOTES.md then run `npm run sync-corpus`.
 */

export interface CorpusQuote {
  quote:  string;   // verbatim, Hebrew, no markdown
  source: string;   // C-number or corpus tag (matched against APPROVED_QUOTE_SOURCES)
  type:   string;   // short label of the quote's role
}

export const CORPUS_QUOTES_BY_MOVE: Record<number, CorpusQuote[]> = {
  "1": [],
  "2": [
    {
      "quote": "אם אין לי חמלה אני עורכת דין תגובתית",
      "source": "C2325-dana-lawyer",
      "type": "reframe"
    }
  ],
  "3": [],
  "4": [
    {
      "quote": "אם אני בתוך האירוע אני מפסידה, אם אני מעל האירוע אני מנצחת",
      "source": "C2325-dana-lawyer",
      "type": "mantra"
    }
  ],
  "5": [],
  "6": [
    {
      "quote": "הפכתי קס לחמלה, והחמלה עזרה לי לנצח תיקים",
      "source": "C2324-dana-lawyer",
      "type": "hook"
    }
  ],
  "7": [],
  "8": [
    {
      "quote": "הרבה אנשים חושבים שחמלה זה מקום חלש, שאם אני פועלת ממנו אני מבטרת, או שאני מפסידה מראש, הפוך",
      "source": "C2324-dana-lawyer",
      "type": "anti-category"
    }
  ],
  "9": [
    {
      "quote": "הכול חייב לנגן (×3 בשילוש מנטרי)",
      "source": "C4367 ⭐ canonical",
      "type": "Identity / Mantra"
    },
    {
      "quote": "אני לא רוצה שיבואו לריח, אני רוצה שיבואו לוויתר.",
      "source": "C4367",
      "type": "Sold-Inversion"
    },
    {
      "quote": "הריח הוא משהו שמייצר אצלנו פעולה.",
      "source": "C4376",
      "type": "Service Reframe"
    },
    {
      "quote": "זה חוש שמכובר באופן ישיר לקבלת ההחלטות שלכם, לזיכרון שלכם ולאיך אתם מרגישים.",
      "source": "C4382-C4383",
      "type": "Authority (neuroscience anchored)"
    },
    {
      "quote": "ובסוף הקהל שלנו קונה אותנו שוב ושוב ושוב כי יש לנו חתימה של ריח.",
      "source": "C4382",
      "type": "Sold-Inversion (loyalty)"
    },
    {
      "quote": "תראו, הפרסום של היום פונה בעיקר לאוזניים ולעיניים. אני עובד על חוש אחר לגמרי, חוש הריח.",
      "source": "C4382-C4383",
      "type": "Anti-category"
    },
    {
      "quote": "מעט מאוד מותגים חוזרים על חתימת הריח שלהם. הם לא מבינים שהריח הוא האיש מחירות שלנו.",
      "source": "C4382",
      "type": "Anti-category + Service Reframe"
    },
    {
      "quote": "כל מה שאמרתי לך פה, כל המצגים האלה, זה נשען על מילה אחת, תחושה.",
      "source": "C4028-ben-yair",
      "type": "mantra"
    }
  ],
  "10": [
    {
      "quote": "תהליך של הנרות זה תהליך שנעשה בעבודת יד, פתיל פתיל, יציקה כפולה, יש טמפרור של השעווה, ממש כמו קונדיטוריה.",
      "source": "C4376",
      "type": "Process-as-Proof + Parable Building"
    },
    {
      "quote": "אבל בקצה, שיקנה בסופו של דבר מהלקוח שלי, הוא יקנה את זה לנצח.",
      "source": "C4376",
      "type": "Loyalty Lock"
    },
    {
      "quote": "אני מחתימה את הלקוחות שהם מוסרים לי מידע מדויק ואמין, כי אני לא יכולה לקחת אחריות על מה שהם לא מספרים לי",
      "source": "C2326-dana-lawyer",
      "type": "body"
    }
  ],
  "11": [
    {
      "quote": "לאט, כל פעולה לאט, סתכל, זה הריח, סתכל, קצת כזה תפתח, תהיה בנחה, עושה ככה, מריח, חכה ותהיה איתי, אל תהיה דם ביותר.",
      "source": "C4382-C4383 ⭐",
      "type": "Receptive Embodiment Direction"
    },
    {
      "quote": "כל מה שאתם צריכים זה... תריח רגע, קודם כל מה, בסדר?",
      "source": "C4382",
      "type": "Receive-Before-Explain"
    }
  ],
  "12": [
    {
      "quote": "אם אני כמטפלת לא מבינה את הנקודה הספציפית של כל אחד, אין שיקום למרחיק, לא קורה, וזה מה שכולם מפספסים.",
      "source": "C4655 ⭐ canonical",
      "type": "Specificity-as-Service"
    }
  ],
  "13": [
    {
      "quote": "הריח הוא האיש מחירות הכי שקט שיש",
      "source": "C4377 ⭐⭐ canonical",
      "type": "Silent Authority Core"
    },
    {
      "quote": "יש לכם כוח על ביד",
      "source": "C4377",
      "type": "Empowerment-via-Revelation"
    },
    {
      "quote": "אין לך שליטה, לא בתגובה הרגשית ולא בתחושה",
      "source": "C4371",
      "type": "Involuntary Capture"
    },
    {
      "quote": "ויותר מזה, את לא יכולה לשלוט ברמת הפעולות שתעשי אחר כך",
      "source": "C4371",
      "type": "Behavioral Chain (post-scent action lock)"
    },
    {
      "quote": "לקוחות קונים את זה בעיניים עצומות",
      "source": "C4381",
      "type": "Eyes-Closed Brand Recognition (repeated 4× for canonical weight)"
    },
    {
      "quote": "זה לא משנה אם זה נרות, דיפיוזרים או פסמים, הם צריכים להשקיע בייצור",
      "source": "C4377",
      "type": "Inversion of Commoditization (delivery vehicle is interchangeable; scent is the differentiator)"
    },
    {
      "quote": "ריח זה לא רק כדי לעשות נעים, אלא כדי ליצור מצב",
      "source": "C4356",
      "type": "Behavioral State Construction"
    },
    {
      "quote": "הלקוח שלו כל הזמן היה חוזר לקנות",
      "source": "C4377",
      "type": "Repeat-Purchase Engine (ROI metric)"
    },
    {
      "quote": "אני יוצר מצב שיותר מחובר למותג",
      "source": "C4356",
      "type": "Brand-Attachment Construction (scent as glue)"
    },
    {
      "quote": "בעצם, לשלוט בתחושות של האדם",
      "source": "C4371",
      "type": "Meta-Move Statement (expert controls scent; scent controls feelings; therefore expert controls outcomes)"
    },
    {
      "quote": "ברגע שיש את הכלים לכולם וברגע שיש את הקריאיטיבים לכולם, השיווק גם נראה אותו דבר",
      "source": "C4078-tzilum-hadar2",
      "type": "body"
    },
    {
      "quote": "כשאני מגיעה כעורכת דין שיש לה חמלה, אני רק הופכת ליותר חכמה ויותר חזקה בתוך התיק",
      "source": "C2324-dana-lawyer",
      "type": "body"
    },
    {
      "quote": "עכשיו אם אני מוחקת את כל זה, אני חלשה, אין לי מידע",
      "source": "C2325-dana-lawyer",
      "type": "body"
    },
    {
      "quote": "אם אתה לא תבוא ותגיד לי את האמת, אני לא אעזור לך",
      "source": "C2326-dana-lawyer",
      "type": "hook"
    }
  ],
  "14": [
    {
      "quote": "אני עושה שימור עובדים שמגיע מיוזמתו של העובד",
      "source": "C0870-liel-talkar ⭐ canonical",
      "type": "Category-Rename + ownership"
    },
    {
      "quote": "ChatGPT זה מגבר. תגביר את הווליום, השאלה היא מי יצר את השיר.",
      "source": "C4079-hadar-author",
      "type": "Rename via metaphor"
    },
    {
      "quote": "אם אתם רוצים שיווק חזק לעסק שלכם, אל תעשו סרטונים.",
      "source": "C1201-hadar-etgar",
      "type": "Anti-naming (paradox hook)"
    },
    {
      "quote": "אין דבר כזה זימון מציאות. זאת לא פעולה, זאת ההוויה.",
      "source": "C2123-reut-zinger",
      "type": "Negation→rename"
    },
    {
      "quote": "לבן אדם לא טוב עם עצמו? הוא יחליף עוד עשר מקומות עבודה. זה לא קשור אליהם, זה קשור אליו.",
      "source": "C0870-liel-talkar",
      "type": "Reframe-the-asker"
    },
    {
      "quote": "במקום למתג כל מוצר בנפרד, לקחנו את הבעלים, שמנו אותו בפרונט, ועשינו האנשת מותג.",
      "source": "C2465-tzilum-hadar",
      "type": "Rename via case-study"
    },
    {
      "quote": "אל תהיה מתווך, תהיה איש עסקים",
      "source": "C4028-ben-yair",
      "type": "anti-category"
    },
    {
      "quote": "להיות עורכת דין תגובתית מבחינתי זה כישלון טוטלי",
      "source": "C2325-dana-lawyer",
      "type": "anti-category"
    }
  ],
  "15": [
    {
      "quote": "אני בודקת שלושה פרמטרים: האישיות (עם איזו מזוודה כל אחד הגיע), הדינמיקה (מה הוא גורם לי להרגיש), וחוקי הזוגיות (עשה ואל תעשה).",
      "source": "C4332-mirvi-inbar ⭐ canonical",
      "type": "Diagnostic Framework"
    },
    {
      "quote": "סוג שיער / פיגמנט / היסטוריה, ואז אני אומרת כן או לא.",
      "source": "C1883-sumud",
      "type": "Diagnostic Framework (lash)"
    },
    {
      "quote": "מנת סי / DNA / מנורות-רשת.",
      "source": "C4338-mirvi-inbar",
      "type": "Diagnostic Framework (DNA-coach variant)"
    },
    {
      "quote": "הוא בן אדם, יש לו צרכים, יש לו אגו, וגם בתיק הוא לא מנטרל את עצמו",
      "source": "C2325-dana-lawyer",
      "type": "body"
    },
    {
      "quote": "יש את הסיפור, יש את הבן אדם, ויש עוד הרבה אנשים שנמצאים איתו בתמונה הזאת",
      "source": "C2325-dana-lawyer",
      "type": "body"
    }
  ]
};

export const INJECTED_QUOTES = `דוגמאות ציטוטים verbatim מהקורפוס לכל מהלך (1-15). מדובר בדוגמאות שהדר אמרה בפועל, לא בהמצאות. חקה את הסגנון, המבנה והקצב, אבל אל תשתמש בציטוטים המדויקים האלה בפלט של הלקוח/ה, אלא אם הם כללים (Sold-Inversion pattern וכד'). כל ציטוט מסומן במקור (C-number) לצורך provenance.

מהלך #2 — Service Reframe:
  - "אם אין לי חמלה אני עורכת דין תגובתית" (C2325-dana-lawyer)

מהלך #4 — Tangible Metaphor Anchor:
  - "אם אני בתוך האירוע אני מפסידה, אם אני מעל האירוע אני מנצחת" (C2325-dana-lawyer)

מהלך #6 — Self-as-Example:
  - "הפכתי קס לחמלה, והחמלה עזרה לי לנצח תיקים" (C2324-dana-lawyer)

מהלך #8 — Anti-Flattery:
  - "הרבה אנשים חושבים שחמלה זה מקום חלש, שאם אני פועלת ממנו אני מבטרת, או שאני מפסידה מראש, הפוך" (C2324-dana-lawyer)

מהלך #9 — Sensory-to-Business Translation:
  - "הכול חייב לנגן (×3 בשילוש מנטרי)" (C4367 ⭐ canonical)
  - "אני לא רוצה שיבואו לריח, אני רוצה שיבואו לוויתר." (C4367)
  - "הריח הוא משהו שמייצר אצלנו פעולה." (C4376)
  - "זה חוש שמכובר באופן ישיר לקבלת ההחלטות שלכם, לזיכרון שלכם ולאיך אתם מרגישים." (C4382-C4383)
  - "ובסוף הקהל שלנו קונה אותנו שוב ושוב ושוב כי יש לנו חתימה של ריח." (C4382)

מהלך #10 — Process-as-Proof:
  - "תהליך של הנרות זה תהליך שנעשה בעבודת יד, פתיל פתיל, יציקה כפולה, יש טמפרור של השעווה, ממש כמו קונדיטוריה." (C4376)
  - "אבל בקצה, שיקנה בסופו של דבר מהלקוח שלי, הוא יקנה את זה לנצח." (C4376)
  - "אני מחתימה את הלקוחות שהם מוסרים לי מידע מדויק ואמין, כי אני לא יכולה לקחת אחריות על מה שהם לא מספרים לי" (C2326-dana-lawyer)

מהלך #11 — Receptive Embodiment:
  - "לאט, כל פעולה לאט, סתכל, זה הריח, סתכל, קצת כזה תפתח, תהיה בנחה, עושה ככה, מריח, חכה ותהיה איתי, אל תהיה דם ביותר." (C4382-C4383 ⭐)
  - "כל מה שאתם צריכים זה... תריח רגע, קודם כל מה, בסדר?" (C4382)

מהלך #12 — Specificity-as-Service:
  - "אם אני כמטפלת לא מבינה את הנקודה הספציפית של כל אחד, אין שיקום למרחיק, לא קורה, וזה מה שכולם מפספסים." (C4655 ⭐ canonical)

מהלך #13 — Silent Authority Positioning:
  - "הריח הוא האיש מחירות הכי שקט שיש" (C4377 ⭐⭐ canonical)
  - "יש לכם כוח על ביד" (C4377)
  - "אין לך שליטה, לא בתגובה הרגשית ולא בתחושה" (C4371)
  - "ויותר מזה, את לא יכולה לשלוט ברמת הפעולות שתעשי אחר כך" (C4371)
  - "לקוחות קונים את זה בעיניים עצומות" (C4381)

מהלך #14 — Category-Rename / Reclaim:
  - "אני עושה שימור עובדים שמגיע מיוזמתו של העובד" (C0870-liel-talkar ⭐ canonical)
  - "ChatGPT זה מגבר. תגביר את הווליום, השאלה היא מי יצר את השיר." (C4079-hadar-author)
  - "אם אתם רוצים שיווק חזק לעסק שלכם, אל תעשו סרטונים." (C1201-hadar-etgar)
  - "אין דבר כזה זימון מציאות. זאת לא פעולה, זאת ההוויה." (C2123-reut-zinger)
  - "לבן אדם לא טוב עם עצמו? הוא יחליף עוד עשר מקומות עבודה. זה לא קשור אליהם, זה קשור אליו." (C0870-liel-talkar)

מהלך #15 — Diagnostic-Framework Reveal:
  - "אני בודקת שלושה פרמטרים: האישיות (עם איזו מזוודה כל אחד הגיע), הדינמיקה (מה הוא גורם לי להרגיש), וחוקי הזוגיות (עשה ואל תעשה)." (C4332-mirvi-inbar ⭐ canonical)
  - "סוג שיער / פיגמנט / היסטוריה, ואז אני אומרת כן או לא." (C1883-sumud)
  - "מנת סי / DNA / מנורות-רשת." (C4338-mirvi-inbar)
  - "הוא בן אדם, יש לו צרכים, יש לו אגו, וגם בתיק הוא לא מנטרל את עצמו" (C2325-dana-lawyer)
  - "יש את הסיפור, יש את הבן אדם, ויש עוד הרבה אנשים שנמצאים איתו בתמונה הזאת" (C2325-dana-lawyer)`;
